### ISSUE TITLE
选中的效果

### ISSUE THREAD

**Issue by ht111111** [hsiangleev/eleTree#24]
![image](https://user-images.githubusercontent.com/75420803/131766793-067b6efb-46bb-4ade-993f-d303d784c1a7.png)

可以说一下这个效果怎么删除的 需要哪个属性吗

**Comment by ht111111** [comment]
是在鼠标移动的时候

**Comment by hsiangleev** [comment]
@ht111111 
鼠标移动时候的高亮没有字段控制，如果不想要，可以加个css样式重置一下
```css
.eleTree-group .eleTree-node .eleTree-title:hover {
    background-color: transparent;
}
```

**Comment by ht111111** [comment]
直接加入不行 ,需要引入什么文件吗  还是说在哪加的

**Comment by hsiangleev** [comment]
@ht111111 你的页面里面没有引入css样式吗，在css样式表里面改就可以了

**Comment by ht111111** [comment]
用layui引入的  没有引入css样式  直接加入没反应 引入dist里面css样式 加里面 还是没反应....

**Comment by ht111111** [comment]
用layui引入的&nbsp; 没有引入css样式&nbsp; 直接加入没反应 引入dist里面css样式 加里面 还是没反应....

**Comment by hsiangleev** [comment]
@ht111111 
没生效可能是权重不够，你的eletree上面有没有其它class，在这个前面在加一个class，如
```css
.eletree .eleTree-group .eleTree-node .eleTree-title:hover {
    background-color: transparent;
}
```
或者直接加个!important吧
```css
.eleTree-group .eleTree-node .eleTree-title:hover {
    background-color: transparent !important;
}
```
